type City = {
  country: string;
  name: string;
};

export const allCities: City[] = [
  // ==================== North America ====================
  { country: "آمریکا", name: "نیویورک" },
  { country: "آمریکا", name: "لس‌آنجلس" },
  { country: "آمریکا", name: "شیکاگو" },
  { country: "آمریکا", name: "میامی" },
  { country: "آمریکا", name: "سان‌فرانسیسکو" },
  { country: "آمریکا", name: "واشنگتن دی‌سی" },
  { country: "آمریکا", name: "بوستون" },
  { country: "آمریکا", name: "لاس‌وگاس" },
  { country: "آمریکا", name: "سیاتل" },
  { country: "آمریکا", name: "دالاس" },
  { country: "آمریکا", name: "هیوستون" },
  { country: "آمریکا", name: "آتلانتا" },
  { country: "آمریکا", name: "اورلاندو" },
  { country: "آمریکا", name: "دنور" },
  { country: "آمریکا", name: "فیلادلفیا" },
  { country: "آمریکا", name: "سن‌دیگو" },
  { country: "کانادا", name: "تورنتو" },
  { country: "کانادا", name: "ونکوور" },
  { country: "کانادا", name: "مونترال" },
  { country: "کانادا", name: "کلگری" },
  { country: "کانادا", name: "اتاوا" },
  { country: "مکزیک", name: "مکزیکوسیتی" },
  { country: "مکزیک", name: "کانکون" },
  { country: "مکزیک", name: "گوادالاخارا" },
  { country: "مکزیک", name: "مونتری" },

  // ==================== South Amrica ====================
  { country: "برزیل", name: "سائو پائولو" },
  { country: "برزیل", name: "ریو دو ژانیرو" },
  { country: "برزیل", name: "برازیلیا" },
  { country: "برزیل", name: "سالوادور" },
  { country: "آرژانتین", name: "بوئنوس آیرس" },
  { country: "آرژانتین", name: "کوردوبا" },
  { country: "شیلی", name: "سانتیاگو" },
  { country: "پرو", name: "لیما" },
  { country: "کلمبیا", name: "بوگوتا" },
  { country: "کلمبیا", name: "مدئین" },
  { country: "اکوادور", name: "کیتو" },
  { country: "ونزوئلا", name: "کاراکاس" },
  { country: "اروگوئه", name: "مونته‌ویدئو" },
  { country: "بولیوی", name: "لاپاز" },
  { country: "پاراگوئه", name: "آسونسیون" },

  // ==================== Europe ====================
  { country: "انگلستان", name: "لندن" },
  { country: "انگلستان", name: "منچستر" },
  { country: "انگلستان", name: "ادینبرو" },
  { country: "فرانسه", name: "پاریس" },
  { country: "فرانسه", name: "نیس" },
  { country: "فرانسه", name: "لیون" },
  { country: "آلمان", name: "برلین" },
  { country: "آلمان", name: "مونیخ" },
  { country: "آلمان", name: "فرانکفورت" },
  { country: "آلمان", name: "هامبورگ" },
  { country: "ایتالیا", name: "رم" },
  { country: "ایتالیا", name: "میلان" },
  { country: "ایتالیا", name: "ونیز" },
  { country: "ایتالیا", name: "ناپل" },
  { country: "اسپانیا", name: "مادرید" },
  { country: "اسپانیا", name: "بارسلونا" },
  { country: "اسپانیا", name: "سویل" },
  { country: "پرتغال", name: "لیسبون" },
  { country: "پرتغال", name: "پورتو" },
  { country: "هلند", name: "آمستردام" },
  { country: "بلژیک", name: "بروکسل" },
  { country: "سوئیس", name: "زوریخ" },
  { country: "سوئیس", name: "ژنو" },
  { country: "اتریش", name: "وین" },
  { country: "یونان", name: "آتن" },
  { country: "ایرلند", name: "دوبلین" },
  { country: "دانمارک", name: "کپنهاگ" },
  { country: "سوئد", name: "استکهلم" },
  { country: "نروژ", name: "اسلو" },
  { country: "فنلاند", name: "هلسینکی" },
  { country: "لهستان", name: "ورشو" },
  { country: "جمهوری چک", name: "پراگ" },
  { country: "مجارستان", name: "بوداپست" },
  { country: "رومانی", name: "بخارست" },
  { country: "ایسلند", name: "ریکیاویک" },
  { country: "کرواسی", name: "زاگرب" },
  { country: "صربستان", name: "بلگراد" },
  { country: "اوکراین", name: "کی‌یف" },
  { country: "روسیه", name: "مسکو" },
  { country: "روسیه", name: "سن‌پترزبورگ" },
  { country: "ترکیه", name: "استانبول" },
  { country: "ترکیه", name: "آنکارا" },

  // ==================== Asia ====================
  { country: "ژاپن", name: "توکیو" },
  { country: "ژاپن", name: "اوساکا" },
  { country: "ژاپن", name: "کیوتو" },
  { country: "کره جنوبی", name: "سئول" },
  { country: "کره جنوبی", name: "بوسان" },
  { country: "چین", name: "پکن" },
  { country: "چین", name: "شانگهای" },
  { country: "چین", name: "گوانگژو" },
  { country: "چین", name: "شنژن" },
  { country: "چین", name: "چنگدو" },
  { country: "هنگ‌کنگ", name: "هنگ‌کنگ" },
  { country: "سنگاپور", name: "سنگاپور" },
  { country: "تایلند", name: "بانکوک" },
  { country: "تایلند", name: "پوکت" },
  { country: "مالزی", name: "کوالالامپور" },
  { country: "اندونزی", name: "جاکارتا" },
  { country: "اندونزی", name: "بالی" },
  { country: "ویتنام", name: "هانوی" },
  { country: "ویتنام", name: "هوشی‌مین" },
  { country: "فیلیپین", name: "مانیل" },
  { country: "هند", name: "دهلی نو" },
  { country: "هند", name: "بمبئی" },
  { country: "هند", name: "بنگلور" },
  { country: "پاکستان", name: "اسلام‌آباد" },
  { country: "بنگلادش", name: "داکا" },
  { country: "نپال", name: "کاتماندو" },
  { country: "سریلانکا", name: "کلمبو" },
  { country: "امارات متحده عربی", name: "دبی" },
  { country: "امارات متحده عربی", name: "ابوظبی" },
  { country: "قطر", name: "دوحه" },
  { country: "عربستان سعودی", name: "ریاض" },
  { country: "عربستان سعودی", name: "جده" },
  { country: "اسرائیل", name: "تل‌آویو" },
  { country: "اردن", name: "امان" },
  { country: "لبنان", name: "بیروت" },
  { country: "گرجستان", name: "تفلیس" },
  { country: "ارمنستان", name: "ایروان" },
  { country: "آذربایجان", name: "باکو" },
  { country: "قزاقستان", name: "آلماتی" },
  { country: "ازبکستان", name: "تاشکند" },

  // ==================== Africa ====================
  { country: "مصر", name: "قاهره" },
  { country: "مصر", name: "اسکندریه" },
  { country: "مراکش", name: "کازابلانکا" },
  { country: "مراکش", name: "مراکش" },
  { country: "الجزایر", name: "الجزیره" },
  { country: "تونس", name: "تونس" },
  { country: "نیجریه", name: "لاگوس" },
  { country: "نیجریه", name: "ابوجا" },
  { country: "کنیا", name: "نایروبی" },
  { country: "اتیوپی", name: "آدیس آبابا" },
  { country: "آفریقای جنوبی", name: "ژوهانسبورگ" },
  { country: "آفریقای جنوبی", name: "کیپ‌تاون" },
  { country: "تانزانیا", name: "دارالسلام" },
  { country: "غنا", name: "آکرا" },
  { country: "سنگال", name: "داکار" },
  { country: "موریس", name: "پورت لوئیس" },

  // ==================== Oceania ====================
  { country: "استرالیا", name: "سیدنی" },
  { country: "استرالیا", name: "ملبورن" },
  { country: "استرالیا", name: "بریزبن" },
  { country: "استرالیا", name: "پرت" },
  { country: "استرالیا", name: "آدلاید" },
  { country: "استرالیا", name: "کانبرا" },
  { country: "نیوزیلند", name: "اوکلند" },
  { country: "نیوزیلند", name: "ولینگتون" },
  { country: "نیوزیلند", name: "کرایست‌چرچ" },
  { country: "فیجی", name: "نادی" },
];
